version: '3'
services:
  frontend:
    container_name: recustomer_frontend
    image: recustomer_frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - API_ORIGIN=http://0.0.0.0:8000
    ports:
      - 3000:3000

